//Compressed CSS Styles
document
		.write('<style type="text/css">.qmmc .qmdivider{display:block;font-size:1px;border-width:0px;border-style:solid;position:relative;z-index:1;}.qmmc .qmdividery{float:left;width:0px;}.qmmc .qmtitle{display:block;cursor:default;white-space:nowrap;position:relative;z-index:1;}.qmclear {font-size:1px;height:0px;width:0px;clear:left;line-height:0px;display:block;float:none !important;}.qmmc {position:relative;zoom:1;z-index:10;}.qmmc a, .qmmc li {float:left;display:block;white-space:nowrap;position:relative;z-index:1;}.qmmc div a, .qmmc ul a, .qmmc ul li {float:none;}.qmsh div a {float:left;}.qmmc div{visibility:hidden;position:absolute;}.qmmc .qmcbox{cursor:default;display:block;position:relative;z-index:1;}.qmmc .qmcbox a{display:inline;}.qmmc .qmcbox div{float:none;position:static;visibility:inherit;left:auto;}/*!!!!!!!!!!! QuickMenu Styles [Please Modify!] !!!!!!!!!!!*//* QuickMenu 0 */#qm0{padding:5px;background-image:url('
				+ base
				+ 'images/center_tile_green.gif);border-width:1px;border-style:solid;border-color:#EEEEEE;}#qm0 a{padding:5px 4px 5px 5px;color:#33392F;font-family:Arial;font-size:16px;font-weight:bolder;text-decoration:none;}#qm0 div{padding:10px;margin:-2px 0px 0px;background-color:transparent;border-style:none;}#qm0 div a{padding:3px 10px 3px 5px;background-color:transparent;font-size:14px;border-width:1px;border-style:dotted;border-color:#EFFFE7;}#qm0 .qmtitle{cursor:default;padding:3px 0px 3px 4px;color:#444444;font-family:arial;font-size:13px;font-weight:bold;}#qm0 .qmdividerx{border-top-width:1px;margin:4px 0px;border-color:#AAB3A4;}#qm0 .qmdividery{border-left-width:1px;height:15px;margin:4px 10px 0px;border-color:#AAAAAA;}#qm0 .qmritem span{border-color:#0FBC3F;background-color:#EFFFE7;}#qm0 .qmritemcontent{padding:0px 0px 0px 4px;}#qm0 .qmhoverfill{background-color:#91ED99;}#qm0 div .qmhoverfill{background-color:#91E599;border-width:1px;border-style:solid;border-color:#555555;}ul#qm0 li:hover > a{background-color:#EFFFE7;}ul#qm0 ul{padding:10px;margin:-2px 0px 0px;background-color:#EFFFE7;border-width:1px;border-style:solid;border-color:#0FBC3F;}#qm0 a:hover {font-weight:900;text-decoration: underline}</style>');

// Compressed Menu Structure
document
		.write('<div id="qm0" class="qmmc"><a href="'
				+ base
				+ 'index.jsp">首页</a><span class="qmdivider qmdividery" ></span><a href="newsList?articleInfoDto.type=xwzx&pageNo=1&pageSize=20">新闻资讯</a><span class="qmdivider qmdividery" ></span><a href="newsList?articleInfoDto.type=zjmz&pageNo=1&pageSize=20">专家门诊</a><span class="qmdivider qmdividery" ></span><a href="newsList?articleInfoDto.type=lyb&pageNo=1&pageSize=20">留言板</a><span class="qmdivider qmdividery" ></span><a href="newsList?articleInfoDto.type=gzkx&pageNo=1&pageSize=20">工作快讯</a><span class="qmdivider qmdividery" ></span><a href="newsList?articleInfoDto.type=jsjb&pageNo=1&pageSize=20">技术简报</a><span class="qmdivider qmdividery" ></span><a href="newsList?articleInfoDto.type=bchsb&pageNo=1&pageSize=20">病虫害识别与防控</a><span class="qmdivider qmdividery" ></span><a href="'
				+ base
				+ 'login.jsp">管理入口</a><span class="qmclear"> </span></div>');
