package njau.org.entity;

// Generated 2013-9-14 11:57:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Announce generated by hbm2java
 */
public class Announce implements java.io.Serializable {

	private int id;
	private String title;
	private String description;
	private String url;
	private Date addTime;
	private Date updateTime;
	

	public Announce() {
	}

	public Announce(int id, String title, Date addTime) {
		this.id = id;
		this.title = title;
		this.addTime = addTime;
	}

	public Announce(int id, String title, String description, String url,
			Date addTime, Date updateTime) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.url = url;
		this.addTime = addTime;
		this.updateTime = updateTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
