package njau.org.entity;

// Generated 2013-9-14 11:57:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import lombok.Data;

/**
 * Document generated by hbm2java
 */
@Data
public class Document implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1744802145754435510L;
	private int documentId;
	private String type;
	private int isTop;
	private int isDelete=1;
	private String title;
	private Date addTime;
	private Date updateTime;
	private String content;
	private String description;
	private String memo;

}
