package njau.org.entity;

import lombok.Data;

// Generated 2013-9-14 11:57:00 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
@Data
public class User implements java.io.Serializable {

	private int userId;
	private String username;
	private String password;
	private Byte powerCode;

	public User() {
	}

	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public User(String username, String password, Byte powerCode) {
		this.username = username;
		this.password = password;
		this.powerCode = powerCode;
	}


}
